Table categories {
  name varchar(255)
  id varchar(11) [pk]
  videos_count int
  articles_count int
  count_date date
}


table tags {
  name varchar(255) [pk]
  videos_count int
  articles_count int
  count_date date
}
