Table categories {
  id varchar(11) [pk]
  title varchar(255)
}

table tags {
  title varchar(255) [pk]
}

table categories_trend {
  id int [pk, increment]
  category_id varchar(11) [ref: > categories.id]
  articles_count int
  videos_count int
  trend_date date
}

table tags_trend {
  id int [pk, increment]
  tag_title varchar(255) [ref: > tags.title]
  articles_count int
  videos_count int
  trend_date date
}
